### ISSUE TITLE
Problems to run example Code

### ISSUE THREAD

**Issue by MaKaNu** [tomwyr/matlab-utils#1]
# Expected Behavior
I have read your [blog(?)](https://medium.com/@tomwyr/asynctask-matlab-parallel-code-execution-made-easier-70cd14101073) and cloned your repo. Then I tried to launch the files `StockExample.m` and `StockFunctionExample.m` to receive a similar output mentioned in your blog:

```Matlab
>> StockExample
[05-Apr-2018 18:37:46] TWTR: potential volume for mean price 28.2900$ and cash 1000000.00$ is 35348.
[05-Apr-2018 18:40:44] TWTR: potential volume for mean price 28.2950$ and cash 1000000.00$ is 35341.
[05-Apr-2018 18:43:45] TWTR: potential volume for mean price 28.3183$ and cash 1000000.00$ is 35312.
[05-Apr-2018 18:46:53] TWTR: potential volume for mean price 28.3375$ and cash 1000000.00$ is 35288.
[05-Apr-2018 18:49:45] TWTR: potential volume for mean price 28.3590$ and cash 1000000.00$ is 35262.
[05-Apr-2018 18:52:44] TWTR: potential volume for mean price 28.4027$ and cash 1000000.00$ is 35207.
```
# Current Behavior
Instead of receiving Stock-values, the Scripts return a Worker failed message.
# Failure Information
The complete Error message:
`Worker failed because: Reference to non-existent field 'TimeSeries_1min_'.`
## Steps to Reproduce
1. Cloned the Repo
1. launched the Example `StockExample.m` file
1. Terminal return: `Worker failed because: Reference to non-existent field 'TimeSeries_1min_'.`
1. Terminal return: `Most recent stock prices are:`
1. launched the Example `StockFunctionExample.m`
1. Terminal return: `Worker failed because: Reference to non-existent field 'TimeSeries_1min_'.`

## Context
relevant Information about my setup:

* MATLAB Version: 9.3.0.713579 (R2017b)
* MATLAB Version 9.3 
* Parallel Computing Toolbox Version 6.11
* Operating System: Microsoft Windows 10 Enterprise

# EDIT
I did a bit debugging and got some weird response from MATLAB:
I discovered that the failed MEssage results from the function call `task.start('TWTR')`.

I stepped further into the function and got the same result when running the code in line 125:
```Matlab
obj.workerJob = obj.startWorkerJob(varargin{:});
```
with `varargin` is 'TWTR'

When I stepped into this function the function call in line 212 results in:

```Matlab
Warning: Struct contents reference from a non-struct array object. 
```
The "Worker failed" message was not returned this time.

This is there I stopped debuging, because my knowledge about the following things is very limited.

**Comment by tomwyr** [comment]
This probably happened because the stock API requests require an api key which is stored as environment variable in the example. According to their page, it's possible to obtain your own key on [this site](https://www.alphavantage.co/support/#api-key). Then you can update `stockApiKey` value with the one you've got:

```Matlab
function url = buildStockApiUrl(stockSymbol)
    ...
    stockApiKey = <put_api_key_here>;
    ...
end
```

**Comment by MaKaNu** [comment]
This worked. But I dont understand how you original planned this. You use original the `getenv` Function  to call the API_KEY. I assumed you somehow set the Env with your key inside the script. I would in this case read a file with my key inside, but dont understand how the env-Functions would help me by this without reading the file.

**Comment by tomwyr** [comment]
So the `getenv` tries to [search for environment variable in your operating system](https://www.mathworks.com/help/matlab/ref/getenv.html), which I initially set with `export` command in terminal. The api key could be placed directly in the script, I just wanted to avoid putting my key on GitHub repo and store it locally rather than that.

This stock example was created just for the purposes of the article. Maybe I could add some note to readme for people that want to run the example themselves.

**Comment by tomwyr** [comment]
There's also [setenv](https://www.mathworks.com/help/matlab/ref/setenv.html) method that sets an environment variable value that can be invoked in Matlab console.

**Comment by MaKaNu** [comment]
Oh Okay I think I understand. You saved your API Key with 
```Matlab
setenv('STOCK_API_KEY',<ENTER_YOUR_API_KEY>)
```
I forked your repo and added a few lines in the example, which makes it easier to understand, how to run the examples.

**Comment by tomwyr** [comment]
Nice to hear it :) Feel free to create pull request with the updated code if you'd like to share your changes.

**Comment by tomwyr** [comment]
Thanks for the contribution!
